### ISSUE TITLE
Add switches (such as content / html) to the regex body search

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/FiltaQuilla#313]
Idea, from issue #115

> > If the content type contains the string "html" I try to remove as many HTML tags (including any <style> section) as possible

> This is incredibly unfortunate, and quite frankly, stupid. I want to filter messages **based on HTML tags**, which you remove before the regex matching. Also, most messages which have both `text/plain` and `text/html` bodies have the former exactly equal to the latter, but obviously without the HTML tags.

Stupid for some, good for others. what we really need is a choice between both methods. and if you are looking for things like HTML attributes, maybe you would benefit for an option that search _only within the HTML markup_ and leaves textContent alone? Let's put our heads together and find a way how to marshal additional information (such as a content / html / html only tag) within the 1 and only parameter that Thunderbird gives us by design. If we stick to the regex syntax, we could probably use the space after the last "/" where the global regex options are. 

> Also, most messages which have both text/plain and text/html bodies have the former exactly equal to the latter, but obviously without the HTML tags.

it's a point but not guaranteed. The problem was that Tb128 removed 

Maybe something like this:

```
/regex/switches{options}
for example, when searching for <div color=blue> or <div style="color:blue"> while ignoring content, we could have:
/[=:]blue/g{html}

```

**Comment by plazer1** [comment]
I see 3 options which to me are reasonable:
1. Do not strip HTML tags from the `text/html` body at all. If you do not want to do this ‒ fair enough.
2. When you fail to match against "`text/html` body without HTML tags", try matching against "raw `text/html` body with HTML tags". This does not require any new user-facing configuration, but may break existing filters:
   * a `matches` filter which did not apply to a message with the old behavior may apply with the new behavior;
   * a `doesn't match` filter which applied with the old behavior may not apply with the new behavior.
4. Add a new filter type "**Raw Body Regexp match**" which will not strip HTML tags when matching against the `text/html` body and otherwise will be equivalent to the "Body Regexp match" filter.

Anything else, such as adding some ad-hoc options to the regex, I find confusing and unintuitive. Worse yet, to even learn about such functionality, you would have to proactively read the manual, which is something most users do only when facing an issue, if at all. But it's your choice, and any option to match against the raw `text/html` body is better than none whatsoever.

> search only within the HTML markup and leaves textContent alone

I'm not sure what you mean by that, but if you are thinking about doing the opposite of what you do now ‒ namely _stripping text and leaving only HTML tags_ ‒ then I'm afraid that is an equally stupid idea. Pardon my French 🙂 What I need to do is to leave the `text/html` body as is. Don't be clever, do not touch it, do not modify it in any way.

**Comment by RealRaven2000** [comment]
> I'm not sure what you mean by that, but if you are thinking about doing the opposite of what you do now ‒ namely _stripping text and leaving only HTML tags_ ‒ then I'm afraid that is an equally stupid idea. Pardon my French 🙂 What I need to do is to leave the `text/html` body as is. Don't be clever, do not touch it, do not modify it in any way.

COnside this case: a normal user wants to search an email that was sent by his graphics design team for any mention of the word "blue".  He builds a simple regular expression and it comes back positive, just because somebody used that word as part of a html attribute:

```html
<div class="importantcontent" aria-datafield="blue">
red green yellow
</div>
```

now what? He may also look for the word "aria", and he may absolutely have no care in the world what kind of html markup surrounds the content. That's why we need different options (plain text, html, exclude css?) one may also want to exclude `<style>` blocks completely! I use a ton of complicated markup in my support templates, filtering for that stuff would simply not be helpful in most cases.

**Comment by RealRaven2000** [comment]
for example I include the attached style sheet in many of my support templates (the code is injected with SmartTemplates). For many users is not much point using a regex that searches for the word "announcement" and then finding it every one of my emails, although I never typed it once. So personally I would like a regex search that doesn't detect it as it wouldn't be useful. OTTOH you may specifically search for a css rule that contains this word, and might not care for the word in the text content. Why not support both cases?

```css
/* support style sheet for Add-ons */

  body {
    padding-left: 0.8em !important;
  }

  #st4message * {
    font-size: medium;
    font-size: max(16px, 1rem);
  }

  #st4message h1 {
      font-size: 1.8rem;
  }

  #st4message h2 {
      font-size: 1.5rem;
  }


  #st4message h3 {
      font-size: 1.3rem;
  }

  #st4message h4 {
      font-size: 1.15rem;
  }

  .renewalBtn {
    padding-block: 0.2em;
    padding-inline: 0.5em;
    background-color: rgb(67, 101, 0) !important;
    background: linear-gradient(to bottom, rgba(184,211,27,1) 0%,rgba(122,166,18,1) 50%,rgba(92,138,0,1) 51%,rgba(135,181,19,1) 100%) !important;
    color: white !important;
    font-weight: bold;
    font-size: 0.75em;
    border-radius: 0.4em;
  }

  .renewalMenu {
    padding-block: 0.2em;
    padding-inline: 0.5em;
    font-size: 0.75em;
    border-radius: 0.1em;
    background: linear-gradient(to bottom, #f4ad6b 0%,#fca72f 22%,#f76d04 51%,#ec9d26 100%) !important;
    color: white !important;
  }


  .shadow-img {
    border: 1px solid rgba(80, 80, 80, 0.3); 
    box-shadow: rgba(80, 80, 80, 0.3) 5px 5px 5px;
  }

  /*  github issueButton - use with span */
  .issueButton {
    color: #fff;
    display:inline-block;
    background-color: #28a745;
    background-image: linear-gradient(-180deg,#34d058,#28a745 90%);
    border-radius: 6px;
    padding: 6px 12px;
    font-size: 14px;
    font-weight: 600;
    line-height: 20px;
    white-space: nowrap;
    vertical-align: middle;
  }

  .productName {
    color: rgb(255, 217, 0);
    background-color: rgba(60,60,60,0.7);
    font-weight: bold;
    padding: 2px 4px;
    border-radius: 4px;
    margin-left: 2px;
    margin-right: 2px;
    border: 1px solid rgba(200,200,200,0.2);
  }

  .announcement .productName {
    color: rgb(255, 217, 0);
    background-color: rgba(60,60,60,0.3);
    margin-left: -2px;
    margin-right: -2px;
  }

  /* code block */
  pre.code {
    background-color: white;
    box-shadow:    inset 4px 4px 6px rgba(0,0,0,0.7);
    color: #303030;
    font-family: Consolas, 'Courier New', Geneva, sans-serif !important;
    padding: 1em;
    white-space: pre-wrap;
  }  


  span.important {
    background-color: #222;
    color: yellow;
    padding: 2px;
    font-style: italic;
    box-shadow: inset 0 1px 2px #080808;
  }

  .psa {
		background: rgba(70,70,70,0.9) !important;
    border-radius: 6px;
    color: rgb(245,245,250);
    font-size: 16px;
    line-height: 150%;
    margin-top: 0.5em;
    padding: 0.5em 1em !important;
  }
  .psa * {
    color: rgb(245,245,250);
  }
  .psa b {
    color: #ffff66;
  }
  .psa a {
    color: #66ccff;
  }
  p.psa {
    max-width: 850px
  }
  
  .psa h4 {
    border: 1px solid rgba(230,230,230, 0.7);
    border-radius: 0.2em;
    font-size: 1.7rem;
    width: max-content;
    margin-top: 1.5em;
    padding: 6px 6px;
  }

  .psa .heading {
    font-size: 1.1em;
    text-decoration: underline overline;
    font-style:italic;
    font-weight: bold;
  }
  

  .history {
    background: rgba(70,70,70,0.8) !important;
    box-shadow: inset 0.3em 0.3em 10px rgba(0,0,0,0.7);
    color: white !important;
    font-size: 16px;
    padding: 1em;  
  }

  .history p {
    margin-top: 0.5em;
    margin-bottom: 0.5em;
  }

  .history a[href] {
    color: rgb(249, 113, 39) !important;
    white-space: nowrap; 
  }
  .history h4 {
    font-size: 1.3em;
  }
  .history h5 {
    font-size: 1.1em;
  }
  .history h4, .history h5 {
    color: yellow;
    margin-top: 0.3em;
    margin-bottom: 0.3em;  
  }

  /* use for pre elements */
  .announcement .code,
  .history .code {
    box-shadow: inset 4px 4px 6px rgba(0,0,0,0.5);
    background-color: white;
    color: #303030;
    font-family: Consolas, 'Courier New', Geneva, sans-serif !important;
    font-size: 0.9em;
    padding: 1em;
  }
  /* use for st4 vars */
  .announcement code,
  .history code {
    background: linear-gradient(to bottom, rgba(230,240,163,1) 0%,rgba(210,230,56,1) 50%,rgba(195,216,37,1) 51%,rgba(219,240,67,1) 100%);
    border-radius: 0.3em;
    border: 1px solid #bbb;
    color: #303030;
    margin: 2px 4px;
    display: inline-block;
    font-family: Consolas, 'Courier New', Geneva, sans-serif !important;
    font-size: 0.9em !important;
    padding: 2px 4px;
  }
  .history code.html {
    background-image: none;
    background-color: white;
    border-radius: 0;
    border: transparent !important;
    color: #303030; /* dark gray forhtml snippet */
  }


  /* number labels in screenshots */
  span.number {
    background-color: rgb(180,0,0) !important;
    color: white !important;
    border-radius: 1.3em;
    font-weight: bold;
    padding: 4px 8px;
  }

  code.parameter {
    background: linear-gradient(to bottom, rgba(40,40,40,0.8) 0%, rgba(40,40,40,0.5) 100%);
    color: rgb(230,230,230) !important;
    padding-inline: 3px;
  }

  key {
    background-color: rgb(50,50,50,0.85);
    border-radius: 3px !important;
    color: white;
    font-family: Consolas, 'Courier New', Geneva, sans-serif;
    margin: 2px 0 !important;    
    padding: 2 4px !important;
  }
  
  
  .announcement {
    background-color: rgba(6, 6, 112, 0.9);
    background-image: linear-gradient(55deg, rgba(6, 6, 112, 0.9) 0%, rgba(115, 3, 85, 0.9) 100%);
    color: white;
    margin-bottom: 1.2em;
    border-radius: 6px;
    margin-left: 0;
    padding: 0.1rem 1rem;
  }

  .announcement *  {
    color: white;
  }
  .announcement a[href] {
    color: #fac526 !important;
  }
  .announcement a[href]:hover {
  color: yellow !important;
  text-decoration: underline;
  }

  /* version headings */
  .announcement h4 {
    margin-top: 1.5em;
    font-size: 1.7rem;
  }

  .screenshot {
    border: 1px solid rgba(80, 80, 80, 0.3); 
    box-shadow: rgba(80, 80, 80, 0.3) 5px 5px 5px; 
    border-radius: 0.5em;
  }
```
